//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unitunes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academico
    {
        public Academico()
        {
            this.MediaAdquiridas = new HashSet<Media>();
            this.WhislistDoAcademico = new HashSet<Whislist>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PrimeiroNome { get; set; }
        public string SegundoNome { get; set; }
    
        public virtual ICollection<Media> MediaAdquiridas { get; set; }
        public virtual ICollection<Whislist> WhislistDoAcademico { get; set; }
        public virtual ContaAcademico ContaAcademico { get; set; }
    }
}
