//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unitunes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public bool Publicado { get; set; }
        public decimal Preco { get; set; }
        public string Categoria { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public string Caminho { get; set; }
    
        public virtual Academico Academico { get; set; }
        public virtual Transacao Transacao { get; set; }
        public virtual Autor Autor { get; set; }
        public virtual Whislist Whislist { get; set; }
    }
}
