//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unitunes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Academico> AcademicoSet { get; set; }
        public DbSet<Media> MediaSet { get; set; }
        public DbSet<Transacao> TransacaoSet { get; set; }
        public DbSet<Album> AlbumSet { get; set; }
        public DbSet<Whislist> WhislistSet { get; set; }
        public DbSet<ContaAcademico> ContaAcademicoSet { get; set; }
    }
}
